### ISSUE TITLE
support with spray-routing-shapeless

### ISSUE THREAD

**Issue by NirLevanon-zz** [kikuomax/spray-jwt#2]
I have a different dependency on my project that requires the use of spray-routing-shapeless2 and it seems that spray-routing and spray-routing-shapeless2 can't really work together.

That is the case when I'm using spray-jwt in my project, which requires spray-routing 1.3.2, as seen in build.sbt.

How difficult would it be to rebuild the project with shapeless2 and load it up to a repository for loading through sbt?

Thanks in advance.

**Comment by kikuomax** [comment]
@NirLevanon I'm planing to create a shapeless2 branch.

**Comment by kikuomax** [comment]
@NirLevanon I published `spray-jwt-shapeless2` to the Maven central repository, please try it out.

**Comment by NirLevanon-zz** [comment]
@kikuomax Works like a charm :) :+1:
