### ISSUE TITLE
Exp claim minimum resolution

### ISSUE THREAD

**Issue by thyandrecardoso** [kikuomax/spray-jwt#3]
Hi there,

Is there a reason for the minimum resolution of the token expiration being set on Minutes?

I am asking this mainly because I stumbled the minimum resolution value while writing tests. Dealing with minutes on these situations is not acceptable as you may understand :)
Anyway, I went to read [the spec](http://tools.ietf.org/html/draft-ietf-oauth-json-web-token-06) and the `exp` claim requires an `IntDate` value, which is the number of seconds since epoch...

So, is there a specific reason for this?

Thanks!!

**Comment by kikuomax** [comment]
Good point, @belerophon!

I just thought that no one would need the resolution of seconds in a practical application. But I understood this restriction is impractical for testing.

Changing the minimum resolution should not cause any compatibility problem. So I will change it to seconds.

Thanks

**Comment by kikuomax** [comment]
Hi @belerophon,

I released the version 0.0.3 that allows you to set the token expiration in seconds.

Thanks

**Comment by thyandrecardoso** [comment]
Thank you!!! :)
